### ISSUE TITLE
Allow the creation of more accounts via hieradata

### ISSUE THREAD

**Issue by cmd-ntrf** [ComputeCanada/puppet-magic_castle#171]
Currently, there is only one kind of accounts that can be created with the hieradata / Terrraform input, and these are the guest accounts. It would however be useful to be able to define more accounts through the hieradata.

A solution would be to generalize the class `profile::accounts::guests` to receive a list of hashes that would contain the 4 key variables. Accounts could then be defined as :

```yaml
profile::accounts::guests:
  - prefix: user
    nb_accounts: 10
    passwd: guest-passwd 
    sponsor: sponsor00
  - prefix: admin
    nb_accounts: 5
    passwd: admin-passwd
    sponsor: staff

```
