### ISSUE TITLE
Implement Prometheus alerting via AlertManager

### ISSUE THREAD

**Issue by cmd-ntrf** [ComputeCanada/puppet-magic_castle#297]
https://prometheus.io/docs/alerting/latest/alertmanager/

**Comment by etiennedub** [comment]
Alertmanager is already supported by [puppet prometheus](https://forge.puppet.com/modules/puppet/prometheus/readme).

To make it works, you can simply use those hiera data from magic castle:
```
---
prometheus::alerts:
  groups:
    - name: 'alerts_test'
      rules:
      - alert: HighLoadAlert
        expr: node_load1 > 0.8
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "High load detected on {{ $labels.instance }}"
          description: "Node load is above 0.8 ({{ $value }}) for more than 10 sec."

prometheus::alertmanagers_config:
  - static_configs:
      - targets:
          - 'localhost:9093'

prometheus::alertmanager::version: '0.26.0'

prometheus::alertmanager::route:
  group_by:
    - 'alertname'
    - 'cluster'
    - 'service'
  group_wait: '5s'
  group_interval: '5m'
  repeat_interval: '3h'
  receiver: 'logging'

prometheus::alertmanager::receivers:
  - name: 'logging'
    webhook_configs:
      - url: 'http://localhost:5001'
```

This config will set up a simple webhook receiver on port 5001 (using `nc -l -p 5001` for debugging on the same node), but it can also be configured for Slack or email.

There are two main issues:

1. The `prometheus::alerts` parameter is already defined for [Slurm alerts](https://github.com/ComputeCanada/puppet-magic_castle/blob/c16be5ad27fcf8b4f99adfc0748cc19ccffb17bd/data/common.yaml#L100). Defining it in Hiera data will overwrite the original definition and remove the Slurm alerts.

2. We need to add `prometheus::alertmanager` to the corresponding tag in [`site.yaml`](https://github.com/ComputeCanada/puppet-magic_castle/blob/c16be5ad27fcf8b4f99adfc0748cc19ccffb17bd/data/site.yaml#L31). This will ensure that Alertmanager runs by default. However, we need to clarify whether Alertmanager should run only in specific cases or all the time.
